# Generated by Django 3.1.2 on 2020-10-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_paletter', '0002_auto_20201025_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettes',
            name='source',
            field=models.URLField(max_length=500),
        ),
    ]
